name: "Build and release"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: "Build for ${{ matrix.os }}/${{ matrix.arch }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            binary: crx-linux-amd64
          - os: windows
            arch: amd64
            binary: crx-windows-amd64.exe
          - os: darwin
            arch: amd64
            binary: crx-darwin-amd64
          - os: darwin
            arch: arm64
            binary: crx-darwin-arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Build Binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -v -trimpath -ldflags="-s -w" -o ${{ matrix.binary }} main.go
          echo "Build successful: ${{ matrix.binary }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary }}
          path: ${{ matrix.binary }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets

      - name: List artifacts
        run: |
          ls -alR release-assets

      - name: Create release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            release-assets/crx-linux-amd64/crx-linux-amd64
            release-assets/crx-windows-amd64.exe/crx-windows-amd64.exe
            release-assets/crx-darwin-amd64/crx-darwin-amd64
            release-assets/crx-darwin-arm64/crx-darwin-arm64
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
